[tools]
python = "3.10"
node = 'lts'
go = 'prefix:1.20'
rust = "nightly"
java = 'zulu-17'
dotnet = '7.0.201'
#ruby = 'latest'
perl = 'latest'
lua = '5.4'
maven = "3.9"
gradle = "8.7"
sbt = "latest"

[settings]
experimental = true
